//! Generate and verify CLI documentation from the shipped Clap model.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use clap::{Command, Parser};

const DEFAULT_OUTPUT: &str = "docs/cli/command-reference.md";

#[derive(Debug, Parser)]
#[command(about = "Generate or verify Colosseum CLI command documentation")]
struct Args {
    /// Compare generated content with the committed file without writing it.
    #[arg(long)]
    check: bool,

    /// Output file, relative to the current directory by default.
    #[arg(long, default_value = DEFAULT_OUTPUT)]
    output: PathBuf,
}

fn main() -> ExitCode {
    let args = Args::parse();
    let generated = render_reference(colosseum_cli::command_spec());

    if args.check {
        return check(&args.output, &generated);
    }

    if let Some(parent) = args.output.parent()
        && let Err(error) = fs::create_dir_all(parent)
    {
        eprintln!("could not create {}: {error}", parent.display());
        return ExitCode::FAILURE;
    }
    if let Err(error) = fs::write(&args.output, generated) {
        eprintln!("could not write {}: {error}", args.output.display());
        return ExitCode::FAILURE;
    }
    println!("generated {}", args.output.display());
    ExitCode::SUCCESS
}

fn check(path: &Path, expected: &str) -> ExitCode {
    match fs::read_to_string(path) {
        Ok(actual) if actual == expected => {
            println!("{} is current", path.display());
            ExitCode::SUCCESS
        }
        Ok(_) => {
            eprintln!(
                "{} is stale; run `cargo run -p colosseum-docs`",
                path.display()
            );
            ExitCode::FAILURE
        }
        Err(error) => {
            eprintln!("could not read {}: {error}", path.display());
            ExitCode::FAILURE
        }
    }
}

fn render_reference(mut root: Command) -> String {
    root.build();
    let mut output = String::from(
        "<!-- Generated by `cargo run -p colosseum-docs`; do not edit by hand. -->\n\n\
         # Command reference\n\n\
         This page is generated from the exact Clap command model used by the shipped\n\
         `colosseum-cli` executable. Conceptual guidance and examples live in the\n\
         [CLI guide](README.md).\n\n",
    );
    let root_name = root.get_name().to_owned();
    render_command(&root, &root_name, &mut output);
    output.truncate(output.trim_end().len());
    output.push('\n');
    output
}

fn render_command(command: &Command, invocation: &str, output: &mut String) {
    let mut rendered = command.clone();
    rendered = rendered.bin_name(invocation);
    let help = rendered
        .render_long_help()
        .to_string()
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");

    writeln!(output, "## `{invocation}`\n").expect("writing to a string cannot fail");
    writeln!(output, "```text\n{}\n```\n", help.trim_end())
        .expect("writing to a string cannot fail");

    for subcommand in command
        .get_subcommands()
        .filter(|subcommand| !subcommand.is_hide_set() && subcommand.get_name() != "help")
    {
        render_command(
            subcommand,
            &format!("{invocation} {}", subcommand.get_name()),
            output,
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reference_contains_nested_public_commands_but_not_stub() {
        let reference = render_reference(colosseum_cli::command_spec());
        assert!(reference.contains("## `colosseum-cli match`"));
        assert!(reference.contains("## `colosseum-cli stats plan sprt`"));
        assert!(reference.contains("## `colosseum-cli tournament run`"));
        assert!(!reference.contains("__uci-stub"));
    }
}
