[package]
name = "colosseum-uci"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
colosseum-core = { path = "../colosseum-core" }
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "process", "io-util", "sync", "time"] }
tracing = "0.1.44"

[dev-dependencies]
tempfile = "3.27.0"
